import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavTopBar from "../components/layout/NavTopBar";
import Navbar from "../components/layout/Navbar";

import Footer from "../components/layout/Footer";
import FloatingButtons from "../components/common/FloatingButtons";
import Script from "next/script";

const poppins = localFont({
  src: [
    {
      path: "../../public/fonts/poppins/poppins-400.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/poppins/poppins-500.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/poppins/poppins-600.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/poppins/poppins-700.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-poppins",
  display: "swap",
});


export const metadata: Metadata = {
  alternates: {
    canonical: '/',
  },
  metadataBase: new URL('https://graft3d.com'),
  title: "Medical 3D Printing Company & Custom Medical Device",
  description: "Generated by create next app",
  openGraph: {
    images: [
      {
        url: '/opengraph-image.png',
        width: 1200,
        height: 630,
        alt: 'Medical 3D Printing Company & Custom Medical Device',
      },
    ],
  },

};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        {/* Google tag (gtag.js) */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-L6MBPSRTBR"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-L6MBPSRTBR');
          `}
        </Script>
        <NavTopBar />
        <Navbar />
        {children}



        <Footer />
        <FloatingButtons />
      </body>
    </html>
  );
}
